version: '3.6'

services:
  snaas-api:
    build: ./snaas-api/
    image: snaas-api:latest
    volumes:
      - ./snaas-api:/snaas-api
    working_dir: /snaas-api
    ports:
      - "3001:3001"
    command: puma -p 3001
    depends_on:
      - snaas-postgres
    environment:
      - DATABASE_URL=postgres://postgres@snaas-postgres
      - SNAAS_UI_SNAAS_API_KEY

  snaas-ui-react:
    build:
      context: ./snaas-ui-react/
      dockerfile: Dockerfile.dev
    image: snaas-ui-react:latest
    environment:
      - REACT_APP_SNAAS_API_KEY=${SNAAS_UI_SNAAS_API_KEY}
    volumes:
        #- ./snaas-ui-react:/snaas-ui-react
      - ./snaas-ui-react/src:/snaas-ui-react/src
      - ./snaas-ui-react/build:/snaas-ui-react/build
      - ${PWD}/snaas-ui-react/package.json:/snaas-ui-react/package.json
      - ${PWD}/snaas-ui-react/package-lock.json:/snaas-ui-react/package-lock.json
    command: npm start
    ports:
      - "3000:3000"


  snaas-postgres:
    image: postgres:10.3-alpine
